spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Daten4you2024
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  mail:
    host: smtp.gmail.com
    port: 587
    username: only.for.it.2023@gmail.com
    password: ravdokrwfajjrcgg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            protocols: TLSv1.2
            trust: smtp.gmail.com
        debug: true

  logging:
    file:
      name: logs/log.log
    level:
      root: DEBUG

key:
  access: Dm7QXW4YowIjJcIV/Qbs4u9R/RCCTPqeg7mkhaCJ6tA=
  refresh: 3zT4pEV8P/GQ6hTpjaZTsY8KRft4l6l0qtaCgWk5djg=

app:
  base-url: http://localhost:8080