spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat
    username: root
    password: Daten4you2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  mail:
    host: smtp.gmail.com
    port: 587
    username: only.for.it.2023@gmail.com
    password: avpximxaoiuipvac
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.protocols: TLSv1.2
      mail.smtp.ssl.trust: smtp.gmail.com
      mail.debug: true

key:
  access: Dm7QXW4YowIjJcIV/Qbs4u9R/RCCTPqeg7mkhaCJ6tA=
  refresh: 3zT4pEV8P/GQ6hTpjaZTsY8KRft4l6l0qtaCgWk5djg=

app:
  base-url: http://localhost:8080

logging:
  file:
    name: logs/log.log
  level:
    root: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  console:
    enabled: true

